# Projet 05 - Scrapping des distances entre Pays et les capitales du monde

Données issues du site https://www.annuaire-mairie.fr/distance-capitale-paris.html  
Les distances sont des distances à vol d'oiseau et ont été vérifiées par sondage avec Google Map.

In [1]:
import numpy as np
import pandas as pd
import requests as req
from bs4 import BeautifulSoup

In [2]:
myrequete = req.get("https://www.annuaire-mairie.fr/distance-capitale-paris.html")
mypage = myrequete.content
mysoup = BeautifulSoup(mypage)

liste_pays = [elt["title"] for elt in mysoup.find_all("img", {"class": "img_drp"})]
liste_distances = [elt.text for elt in mysoup.find_all("strong")]
liste_distances = pd.to_numeric([elt[:-3].replace(" ","") for elt in liste_distances if elt[-3:]==" km"])

if (len(liste_pays) == len(liste_distances)):
    print ("OK : les 2 tableaux ont la même longueur")
else:
    print ("Erreur : les 2 tableaux ont une longueur différente")

OK : les 2 tableaux ont la même longueur

In [3]:
data_distances = pd.DataFrame(liste_pays, columns=["pays"])
data_distances["distance_capitale_paris"] = liste_distances

In [4]:
data_fao = pd.read_csv("projet05_liste_pays_FAO.csv")
pays_fao = data_fao[["Code zone","Zone"]]
pays_fao.columns = ["country_code","pays"]

In [5]:
data_distances = pd.merge(data_distances, pays_fao, how="left", on="pays")
data_distances.isna().sum()

pays                        0
distance_capitale_paris     0
country_code               28
dtype: int64

In [6]:
data_distances[data_distances.country_code.isna()].sort_values(by="pays")

                           pays  distance_capitale_paris  country_code
140                    Birmanie                     8644           NaN
40                  Biélorussie                     1829           NaN
5                       Bolivie                    10074           NaN
141                      Brunei                    11223           NaN
87                     Cap-Vert                     4453           NaN
145               Corée du Nord                     8781           NaN
146                Corée du Sud                     8976           NaN
151                        Irak                     3868           NaN
152                        Iran                     4216           NaN
159                        Laos                     9248           NaN
103                     Liberia                     4896           NaN
58                    Macédoine                     1670           NaN
186                  Micronésie                    13396           NaN
60                     Moldavie                     1977           NaN
114                     Nigeria                     4457           NaN
23                       Panamá                     8671           NaN
70                       Russie                     2490           NaN
67           République tchèque                      883           NaN
27   Saint-Christophe-et-Niévès                     6762           NaN
30                     Salvador                     8986           NaN
126                   Swaziland                     8848           NaN
173                       Syrie                     3279           NaN
127                    Tanzanie                     6936           NaN
176              Timor oriental                    13130           NaN
78                      Vatican                     1106           NaN
34                    Venezuela                     7626           NaN
179                    Viêt Nam                     9208           NaN
14                   États-Unis                     6169           NaN

In [7]:
for lin, row in data_distances.iterrows():
    if row.pays=="Birmanie":
        data_distances.loc[lin, "pays"] = "Myanmar"
    if row.pays=="Biélorussie":
        data_distances.loc[lin, "pays"] = "Bélarus"
    if row.pays=="Bolivie":
        data_distances.loc[lin, "pays"] = "Bolivie (État plurinational de)"
    if row.pays=="Brunei":
        data_distances.loc[lin, "pays"] = "Brunéi Darussalam"
    if row.pays=="Cap-Vert":
        data_distances.loc[lin, "pays"] = "Cabo Verde"
    if row.pays=="Corée du Nord":
        data_distances.loc[lin, "pays"] = "République populaire démocratique de Corée"
    if row.pays=="Corée du Sud":
        data_distances.loc[lin, "pays"] = "République de Corée"
    if row.pays=="Irak":
        data_distances.loc[lin, "pays"] = "Iraq"
    if row.pays=="Iran":
        data_distances.loc[lin, "pays"] = "Iran (République islamique d')"
    if row.pays=="Laos":
        data_distances.loc[lin, "pays"] = "République démocratique populaire lao"
    if row.pays=="Liberia":
        data_distances.loc[lin, "pays"] = "Libéria"
    if row.pays=="Macédoine":
        data_distances.loc[lin, "pays"] = "Macédoine du Nord"
    if row.pays=="Micronésie":
        data_distances.loc[lin, "pays"] = "Micronésie (États fédérés de)"
    if row.pays=="Moldavie":
        data_distances.loc[lin, "pays"] = "République de Moldova"
    if row.pays=="Nigeria":
        data_distances.loc[lin, "pays"] = "Nigéria"
    if row.pays=="Panamá":
        data_distances.loc[lin, "pays"] = "Panama"
    if row.pays=="Russie":
        data_distances.loc[lin, "pays"] = "Fédération de Russie"
    if row.pays=="République tchèque":
        data_distances.loc[lin, "pays"] = "Tchéquie (la)"
    if row.pays=="Saint-Christophe-et-Niévès":
        data_distances.loc[lin, "pays"] = "Saint-Kitts-et-Nevis"
    if row.pays=="Salvador":
        data_distances.loc[lin, "pays"] = "El Salvador"
    if row.pays=="Swaziland":
        data_distances.loc[lin, "pays"] = "Eswatini"
    if row.pays=="Syrie":
        data_distances.loc[lin, "pays"] = "République arabe syrienne"
    if row.pays=="Tanzanie":
        data_distances.loc[lin, "pays"] = "République-Unie de Tanzanie"
    if row.pays=="Timor oriental":
        data_distances.loc[lin, "pays"] = "Timor-Leste"
    if row.pays=="Vatican":
        data_distances.loc[lin, "pays"] = "Saint-Siège"
    if row.pays=="Venezuela":
        data_distances.loc[lin, "pays"] = "Venezuela (République bolivarienne du)"
    if row.pays=="Viêt Nam":
        data_distances.loc[lin, "pays"] = "Viet Nam"
    if row.pays=="États-Unis":
        data_distances.loc[lin, "pays"] = "États-Unis d'Amérique"
    if row.pays=="Chine":
        data_distances.loc[lin, "pays"] = "Chine, continentale"

In [8]:
data_distances.drop(columns="country_code", inplace=True)
data_distances = pd.merge(data_distances, pays_fao, how="left", on="pays")
data_distances.isna().sum()

pays                       0
distance_capitale_paris    0
country_code               0
dtype: int64

In [9]:
data_distances.to_csv("projet05_distances_capitales.csv", index=False)